# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.databaseConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.databaseConnectButton.setGeometry(QtCore.QRect(10, 10, 211, 61))
        self.databaseConnectButton.setObjectName("databaseConnectButton")
        self.databaseTableView = QtWidgets.QTableView(self.centralwidget)
        self.databaseTableView.setGeometry(QtCore.QRect(450, 10, 671, 851))
        self.databaseTableView.setObjectName("databaseTableView")
        self.nameLineAdd = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineAdd.setGeometry(QtCore.QRect(10, 80, 113, 20))
        self.nameLineAdd.setObjectName("nameLineAdd")
        self.regionLineAdd = QtWidgets.QLineEdit(self.centralwidget)
        self.regionLineAdd.setGeometry(QtCore.QRect(10, 110, 113, 20))
        self.regionLineAdd.setObjectName("regionLineAdd")
        self.cityLineAdd = QtWidgets.QLineEdit(self.centralwidget)
        self.cityLineAdd.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.cityLineAdd.setObjectName("cityLineAdd")
        self.grntiLineAdd = QtWidgets.QLineEdit(self.centralwidget)
        self.grntiLineAdd.setGeometry(QtCore.QRect(10, 170, 113, 20))
        self.grntiLineAdd.setObjectName("grntiLineAdd")
        self.infoButtonDbAdd = QtWidgets.QPushButton(self.centralwidget)
        self.infoButtonDbAdd.setGeometry(QtCore.QRect(10, 200, 111, 23))
        self.infoButtonDbAdd.setObjectName("infoButtonDbAdd")
        self.showDbButton = QtWidgets.QPushButton(self.centralwidget)
        self.showDbButton.setGeometry(QtCore.QRect(230, 10, 211, 61))
        self.showDbButton.setObjectName("showDbButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.databaseConnectButton.setText(_translate("MainWindow", "Connect to database"))
        self.nameLineAdd.setPlaceholderText(_translate("MainWindow", "Иванов И.И."))
        self.regionLineAdd.setPlaceholderText(_translate("MainWindow", "Центральный"))
        self.cityLineAdd.setPlaceholderText(_translate("MainWindow", "Москва"))
        self.grntiLineAdd.setPlaceholderText(_translate("MainWindow", "00.00.00"))
        self.infoButtonDbAdd.setText(_translate("MainWindow", "Add to database"))
        self.showDbButton.setText(_translate("MainWindow", "Show a table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
